"""Initial migration

Revision ID: 22836dc6bfe2
Revises: 
Create Date: 2025-11-09 04:46:07.448563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22836dc6bfe2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact_map_layers')
    op.drop_table('fai_metrics')
    op.drop_table('reports')
    op.drop_table('worker_stats')
    op.drop_table('transactions')
    op.add_column('campaigns', sa.Column('zone', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('assigned_users', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('reward', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('impact_metric', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('zone', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('lng', sa.Float(), nullable=True))
    op.alter_column('reputations', 'badges',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('users', sa.Column('zone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'zone')
    op.alter_column('reputations', 'badges',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('jobs', 'lng')
    op.drop_column('jobs', 'lat')
    op.drop_column('jobs', 'zone')
    op.drop_column('campaigns', 'impact_metric')
    op.drop_column('campaigns', 'reward')
    op.drop_column('campaigns', 'assigned_users')
    op.drop_column('campaigns', 'lng')
    op.drop_column('campaigns', 'lat')
    op.drop_column('campaigns', 'zone')
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_or_destination', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_table('worker_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jobs_done', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reputation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_stats_pkey')),
    sa.UniqueConstraint('name', name=op.f('worker_stats_name_key'))
    )
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_table('fai_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fai_metrics_pkey')),
    sa.UniqueConstraint('month', name=op.f('fai_metrics_month_key'))
    )
    op.create_table('impact_map_layers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('layer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('impact_map_layers_pkey'))
    )
    # ### end Alembic commands ###
